### ISSUE TITLE
"Hψ(Ωψ(Ω..." phase makes the whole page jitter

### ISSUE THREAD

**Issue by jyasskin** [FlamemasterNXF/ordinal-pringles#32]
Something like https://css-tricks.com/snippets/css/prevent-superscripts-and-subscripts-from-affecting-line-height/ might be part of the solution, or setting an explicit height on `#ordinalContainer`.

**Comment by FlamemasterNXF** [comment]
Now that v0.3 is complete I'll look into this :)

**Comment by FlamemasterNXF** [comment]
As far as I can see, there's no real fix for this. Sorry :(
Neither of your proposed solutions will work and I haven't found any of my own.

Due to the lack of any possible fix, I will close this issue for now.
