### ISSUE TITLE
Calling `boosterUnlock` every frame causes a slow memory and performance leak

### ISSUE THREAD

**Issue by WaterFace** [FlamemasterNXF/ordinal-pringles#8]
`boosterUnlock` adds event listeners to a few buttons on the booster page, but it's called every frame and eventually all those event listeners start causing severe performance issues (100+ms frame times, 2s+ to switch tabs, etc.). The issue can be worked around by periodically refreshing the page.

This image, showing hundreds of event listeners, was taken just a few seconds after reloading the page:
![image](https://github.com/FlamemasterNXF/ordinal-pringles/assets/1782224/fa5e3445-e754-4e71-a469-a0ee45c2a907)

**Comment by FlamemasterNXF** [comment]
Fixed by #9
